spring:
  application:
    name: Volleyball

  datasource:
    url: jdbc:postgresql://localhost:5432/volleyball
    username: postgres
    password: 1111

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true